import { recordCall } from './usage'
import { keyFor, selectProvider } from './registry'
import { stubbed } from './source'
import type { GifResult } from './types'

/**
 * The app's own chosen art — remembered by name, fetched fresh.
 *
 * The landing wall, the waiting backdrop and the 404 all want *particular*
 * GIFs rather than whatever is trending. That used to mean a committed catalog
 * of `media.giphy.com` URLs, generated by a build script. Under Klipy's terms
 * that arrangement is wrong twice over:
 *
 *   > API requests and media loads must originate from the user's mobile app,
 *   > desktop app, or web browser. Do not route requests through
 *   > partner-operated servers, proxies, CDNs, or other intermediaries without
 *   > prior written approval from KLIPY.
 *
 *   > Do not store, mirror, re-host, rewrite, or retain copies of KLIPY media
 *   > unless KLIPY has approved a different delivery method in writing.
 *
 * A build-time importer is a server-side request, and a committed URL is
 * retained delivery data that keeps serving content after Klipy has pulled it.
 * Their integration requirements ask for prior approval for exactly that.
 *
 * **So what is committed here is slugs, and nothing else.** A slug is a name.
 * The media behind it is resolved in the browser, on every load, through the
 * same `gifs/items` endpoint any client may call — which also means moderation
 * decisions reach these surfaces the way they reach the picker, instead of
 * being frozen into the repository. See ADR-0025.
 */

/**
 * Twenty for the landing wall, curated by hand.
 *
 * Order is the wall's own and is preserved on the way back: a wall that
 * reshuffled itself on every load would be a different wall each time.
 */
export const WALL_SLUGS: readonly string[] = [
  'applause-clapping-60',
  'aua-ouch',
  'bb-baby-1',
  'bravo-applause-4',
  'celebrate-14',
  'celebrate-203',
  'celebrate-259',
  'celebrate-minions',
  'celebrate-party-1',
  'celebration-celebrate-12',
  'chris-pratt-andy-dwyer-1',
  'clap-applause-77',
  'clapping-applause-69',
  'clapping-hands-210',
  'clapping-sass-1',
  'cookie-monster-dancing-2',
  'cringe-embarrassed-5',
  'dean-winchester-95',
  'eddie-murphy-shocked-6',
  'epic-facepalm-2',
]

/**
 * The waiting screen's backdrop: firelight in a dark room.
 *
 * Chosen against the brief the fireworks before it were chosen against — it
 * opens nearly black with one warm ember low in the frame and brightens into a
 * lit close-up, so under a full scrim what survives is the warmth rather than a
 * picture competing with the headline.
 *
 * Not 16:9, unlike the clip it replaces: 640×454, near enough 1.4:1. The
 * backdrop covers and crops, so the frame's own aspect never mattered — what
 * has to agree is the poster with the video, and both come off this one item.
 */
export const BACKDROP_SLUG = 'gunna-fire'

/** The 404's GIF. Near-square, because the card that holds it is one. */
export const NOT_FOUND_SLUG = 'shocked-meme-4'

/**
 * One lookup per slug-set per page load, held in memory.
 *
 * Not a cache in the sense their terms forbid: nothing is persisted and nothing
 * survives the page. It is the ordinary lifetime of a fetch — the wall, the
 * backdrop and the 404 each ask once and every mount after that reuses the
 * answer, which matters because the waiting screen mounts on every round and
 * would otherwise resolve the same backdrop each time.
 *
 * Keyed by the slugs themselves, so the three surfaces do not share an entry.
 */
const inFlight = new Map<string, Promise<GifResult[]>>()

/**
 * Resolve slugs into drawable art, or nothing at all.
 *
 * Returns an empty list rather than throwing for every reason it might fail —
 * stubbed, no key, a provider that cannot look items up, a spent allowance, an
 * outage. Every caller has its own art to fall back on, and none of these
 * surfaces is worth an error boundary: a landing page that renders house SVGs
 * is fine, and a landing page that renders a stack trace is not.
 */
export async function resolveArt(slugs: readonly string[]): Promise<GifResult[]> {
  /**
   * The same switch the picker reads.
   *
   * `NEXT_PUBLIC_GIFS_STUB` and `?gifs=stub` are documented to keep *every*
   * surface off a third party — a keyless clone, and the Playwright suite,
   * which resolves no host but the dev server. A wall that called out anyway
   * would have broken both, and would have spent an allowance the offline shelf
   * is there to protect.
   */
  if (stubbed()) return []

  const provider = selectProvider()
  const lookup = provider?.items
  if (!provider || !lookup) return []

  const apiKey = keyFor(provider.descriptor.id)
  if (!apiKey) return []

  const key = slugs.join(',')
  const held = inFlight.get(key)
  if (held) return held

  const pending = (async () => {
    try {
      const board = await lookup(slugs, apiKey)
      recordCall(provider.descriptor.id, 'items', 'ok')
      return [...board.items]
    } catch {
      // Counted, because a call that failed still spent the allowance — the one
      // thing `usage.ts` exists to get right. Dropped from the map so a failure
      // is not remembered as the answer for the rest of the session.
      recordCall(provider.descriptor.id, 'items', 'failed')
      inFlight.delete(key)
      return []
    }
  })()

  inFlight.set(key, pending)
  return pending
}
